version: '3.5'
services:
  zabbix-server:
    image: zabbix/zabbix-server-mysql:alpine-5.0-latest
    ports:
      - "10051:10051"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./zbx_env/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:ro
      - ./zbx_env/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
      - ./zbx_env/var/lib/zabbix/export:/var/lib/zabbix/export:rw
      - ./zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
      - ./zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
      - ./zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
      - ./zbx_env/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
#      - snmptraps:/var/lib/zabbix/snmptraps:rw
    links:
      - mysql-server:mysql-server
#      - zabbix-java-gateway:zabbix-java-gateway
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    deploy:
      resources:
        limits:
          cpus: '0.70'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    env_file:
      - .env_db_mysql
#      - .env_srv
    secrets:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
    #   - client-key.pem
    #   - client-cert.pem
    #   - root-ca.pem
    depends_on:
      - mysql-server
#      - zabbix-java-gateway
#      - zabbix-snmptraps
    networks:
      zbx_net_backend:
        aliases:
          - zabbix-server
          - zabbix-server-mysql
          - zabbix-server-alpine-mysql
          - zabbix-server-mysql-alpine
      zbx_net_frontend:
    #  devices:
    #   - "/dev/ttyUSB0:/dev/ttyUSB0"
    stop_grace_period: 30s
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65000
      - net.ipv4.conf.all.accept_redirects=0
      - net.ipv4.conf.all.secure_redirects=0
      - net.ipv4.conf.all.send_redirects=0
    labels:
      com.zabbix.description: "Zabbix server with MySQL database support"
      com.zabbix.company: "Zabbix LLC"
      com.zabbix.component: "zabbix-server"
      com.zabbix.dbtype: "mysql"
      com.zabbix.os: "alpine"

  mysql-server:
    image: mysql:8.0
    command:
      - mysqld
      - --character-set-server=utf8
      - --collation-server=utf8_bin
      - --default-authentication-plugin=mysql_native_password
    #   - --require-secure-transport
    #   - --ssl-ca=/run/secrets/root-ca.pem
    #   - --ssl-cert=/run/secrets/server-cert.pem
    #   - --ssl-key=/run/secrets/server-key.pem
    volumes:
      - ./zbx_env/var/lib/mysql:/var/lib/mysql:rw
    env_file:
      - .env_db_mysql
    secrets:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
    #   - server-key.pem
    #   - server-cert.pem
    #   - root-ca.pem
    stop_grace_period: 1m
    networks:
      zbx_net_backend:
        aliases:
          - mysql-server
          - zabbix-database
          - mysql-database

#  zabbix-java-gateway:
#    image: zabbix/zabbix-java-gateway:alpine-5.0-latest
#    ports:
#      - "10052:10052"
#    deploy:
#      resources:
#        limits:
#          cpus: '0.5'
#          memory: 512M
#        reservations:
#          cpus: '0.25'
#          memory: 256M
#    env_file:
#      - .env_java
#    networks:
#      zbx_net_backend:
#        aliases:
#          - zabbix-java-gateway
#          - zabbix-java-gateway-alpine
#    stop_grace_period: 5s
#    labels:
#      com.zabbix.description: "Zabbix Java Gateway"
#      com.zabbix.company: "Zabbix LLC"
#      com.zabbix.component: "java-gateway"
#      com.zabbix.os: "alpine"
#
#  zabbix-snmptraps:
#    image: zabbix/zabbix-snmptraps:alpine-5.0-latest
#    ports:
#      - "162:1162/udp"
#    volumes:
#      - snmptraps:/var/lib/zabbix/snmptraps
#    deploy:
#      resources:
#        limits:
#          cpus: '0.5'
#          memory: 256M
#        reservations:
#          cpus: '0.25'
#          memory: 128M
#    networks:
#      zbx_net_frontend:
#        aliases:
#          - zabbix-snmptraps
#      zbx_net_backend:
#    stop_grace_period: 5s
#    labels:
#      com.zabbix.description: "Zabbix snmptraps"
#      com.zabbix.company: "Zabbix LLC"
#      com.zabbix.component: "snmptraps"
#      com.zabbix.os: "alpine"

networks:
  zbx_net_frontend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.16.228.0/24
  zbx_net_backend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    internal: true
    ipam:
      driver: default
      config:
        - subnet: 172.16.229.0/24

#volumes:
#  snmptraps:

secrets:
  MYSQL_USER:
    file: ./.MYSQL_USER
  MYSQL_PASSWORD:
    file: ./.MYSQL_PASSWORD
  MYSQL_ROOT_PASSWORD:
    file: ./.MYSQL_ROOT_PASSWORD

