# ARG only for FROM
ARG ARG_VERSION=latest
FROM centos:$ARG_VERSION as base

# MAINTAINER david<david.wei@ebaotech.com> deprecated

ENV MY_PATH=/usr/local/cronsun VERSION=1.06

WORKDIR $MY_PATH

#COPY ./cronsun-v0.3.5 $MY_PATH/cronsun-v0.3.5
ADD https://github.com/shunfei/cronsun/releases/download/v0.3.5/cronsun-v0.3.5-linux-amd64.zip $MY_PATH

FROM base
#FROM centos:$ARG_VERSION
#COPY --from=base $MY_PATH/cronsun-v0.3.5-linux-amd64.zip $MY_PATH/cronsun-v0.3.5-linux-amd64.zip
COPY cronsun.sh $MY_PATH/cronsun.sh
COPY start.sh $MY_PATH/start.sh
RUN /usr/bin/chmod 777 -R /usr/local/cronsun/* && sh /usr/local/cronsun/cronsun.sh

# nohup cronsun-v0.3.5/cronweb -conf cronsun-v0.3.5/conf/base.json > log/cronweb1.log 2>&1 &
#ENTRYPOINT ["/usr/bin/sh"]
#CMD ["/usr/local/cronsun/start1.sh"]

LABEL com.gwaysoft.cronsun=$VERSION com.gwaysoft.email="david.wei@ebaotech.com"

EXPOSE 7079

CMD /usr/local/cronsun/start.sh
