version: "3.8"
services:
  cronsun:
    container_name: cronsun
    image: cronsun:${CRON_TAG}
    build:
      context: ./cronsun
      dockerfile: Dockerfile-cronsun
#      args:
#        buildno: 1.01
#    restart: always
    ports:
      - 7079:7079
#   container does not stop, where container run
    volumes:
      - ./data/task:/usr/local/cronsun/task
#      - ./cronsun/cronsun.sh:/usr/local/cronsun/cronsun.sh
    tty: true
    labels:
      com.gwaysoft.cronsun.docker.compose: from docker-compose.yaml
#    stdin_open: true
    depends_on:
      - mongo
      - etcd
#    command:
#      /usr/bin/sh
#      - /usr/local/cronsun/start.sh
    networks:
      - cronsun
  mongo:
    container_name: cronsun_mongo
    image: cronsun_mongo:${CRON_TAG}
    build:
      context: ./mongo
      dockerfile: Dockerfile-mongo
    restart: always
    ports:
      - 27017:27017  # 本地端口(可自定义):容器内默认端口(mongo设定为27017)
    volumes:
      - ./mongo/setup:/docker-entrypoint-initdb.d/  # 本地文件路径:容器内映射路径
      - ./data/mongo:/data/db/
    environment:  # admin账号和密码
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    networks:
      - cronsun
    #privileged: true
  etcd:
    container_name: cronsun_etcd
    #    image: registry.cn-hangzhou.aliyuncs.com/coreos_etcd/etcd:v3
    image: quay.io/coreos/etcd
    ports:
      - "2379:2379"
      - "4001:4001"
      - "2380:2380"
    environment:
      - TZ=CST-8
      - LANG=zh_CN.UTF-8
    #      - host_ip=0.0.0.0
    command:
      /usr/local/bin/etcd
      -name etcd0
      -data-dir /etcd-data
      -advertise-client-urls http://${host_ip}:2379,http://${host_ip}:4001
      -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001
      -initial-advertise-peer-urls http://${host_ip}:2380
      -listen-peer-urls http://0.0.0.0:2380
      -initial-cluster-token docker-etcd
      -initial-cluster etcd0=http://${host_ip}:2380
      -initial-cluster-state new
    volumes:
      - "./data/etcd:/etcd-data"
      # - "/data/config/etcd/ca-certificates/:/etc/ssl/certs"
    labels:
      - com.gwaysoft.cronsun.etcd=add etcd for cronsun
    networks:
      - cronsun
networks:
  cronsun: