apiVersion: v1
kind: Service
metadata:
  name: zabbix-web
  labels:
    app: zabbix
  namespace: zabbix
spec:
  ports:
    - port: 80
      targetPort: 8080
      name: web-http
    - port: 443
      targetPort: 8443
      name: web-https
  selector:
    name: zabbix-web
  type: NodePort
#  externalIPs:
#    - <Specify external IP here>
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: zabbix-web
  labels:
    app: zabbix
    tier: zabbix-web
  namespace: zabbix
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: zabbix-web
        app: zabbix
    spec:
      containers:
        - name: zabbix-web
          image: zabbix/zabbix-web-nginx-mysql:alpine-5.0-latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: web-http
            - containerPort: 8443
              name: web-https
          resources:
            limits:
              cpu: 200m
              memory: 400Mi
            requests:
              cpu: 200m
              memory: 400Mi
          livenessProbe:
            httpGet:
              path: /
              port: web-http
              scheme: HTTP
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /
              port: web-http
              scheme: HTTP
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          envFrom:
            - secretRef:
                name: db-secret
            - configMapRef:
                name: db-config
          env:
            - name: ZBX_SERVER_NAME
              value: "Zabbix kubernetes"
            - name: PHP_TZ
              value: "Europe/Riga"
            - name: ZBX_JAVAGATEWAY_ENABLE
              value: "true"
          volumeMounts:
            - name: zabbix-web-ssl
              mountPath: /etc/ssl/nginx
              readOnly: true
      volumes:
        - hostPath:
            path: /home/dotneft/zbx/zbx_env/etc/ssl/nginx/
          name: zabbix-web-ssl