apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: zabbix
type: Opaque
#stringData:
#  db-zbx-user: zabbix
#  db-zbx-pass: zabbix
#  db-root-pass: root_pwd
data:
  db-root-pass: cm9vdF9wd2Q=
  db-zbx-pass: emFiYml4
  db-zbx-user: emFiYml4
