apiVersion: v1
kind: Service
metadata:
  name: zabbix-server
  labels:
    app: zabbix
  namespace: zabbix
spec:
  ports:
    - port: 10051
      targetPort: 10051
      name: zabbix-trapper
    - port: 162
      targetPort: 1162
      protocol: UDP
      name: snmp-trap
  selector:
    name: zabbix-server
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: zabbix-server
  labels:
    app: zabbix
    tier: server
    environment: dev
  namespace: zabbix
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: zabbix-server
        app: zabbix
    spec:
      containers:
        - name: zabbix-server
          image: zabbix/zabbix-server-mysql:alpine-5.0-latest
          imagePullPolicy: Always
          ports:
            - containerPort: 10051
              protocol: TCP
              name: zabbix-trapper
          readinessProbe:
            tcpSocket:
              port: zabbix-trapper
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: zabbix-trapper
            initialDelaySeconds: 15
            periodSeconds: 20
          envFrom:
            - secretRef:
                name: db-secret
            - configMapRef:
                name: db-config
          env:
            - name: ZBX_SERVER_NAME
              value: "Zabbix kubernetes"
            - name: PHP_TZ
              value: "Europe/Riga"
            - name: ZBX_JAVAGATEWAY_ENABLE
              value: "true"
            - name: ZBX_STARTJAVAPOLLERS
              value: "5"
            - name: ZBX_ENABLE_SNMP_TRAPS
              value: "true"
            - name: ZBX_STARTPROXYPOLLERS
              value: "5"
            - name: ZBX_PROXYCONFIGFREQUENCY
              value: "60"
          volumeMounts:
            - name: zabbix-db-storage
              mountPath: /var/lib/zabbix/snmptraps/
              readOnly: true
        - name: zabbix-snmptraps
          image: zabbix/zabbix-snmptraps:alpine-5.0-latest
          imagePullPolicy: Always
          ports:
            - containerPort: 1162
              protocol: UDP
              name: snmp-trap
          volumeMounts:
            - name: zabbix-db-storage
              mountPath: /var/lib/zabbix/snmptraps/
              readOnly: false
      volumes:
        - hostPath:
            path: /zabbix/
          name: zabbix-db-storage