kind: Namespace
apiVersion: v1
metadata:
  name: nginx-namespace-cr
---
kind: Service
apiVersion: v1
metadata:
  name: nginx-service-cr
  namespace: nginx-namespace-cr
  labels:
    service: nginx-service-label-cr
spec:
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 80
      name: nginx-service
#      nodePort: 30310
  selector:
    pod: nginx-lable-cr
# clusterIp
#  type: NodePort
#  externalIPs:
#    - 192.168.2.70
#    - 192.168.2.71
#    - 192.168.2.72
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-cr
  namespace: nginx-namespace-cr
spec:
  replicas: 3
  selector:
    pod: nginx-lable-cr
  template:
    metadata:
      name: nginx-name-cr
      labels:
        pod: nginx-lable-cr
    spec:
      containers:
        - name: nginx-name-container-cr
          image: nginx
          ports:
            - containerPort: 80
